# Generated by Django 4.1.5 on 2023-01-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
